/**
 * Language Context - Mehrsprachigkeit (DE/EN)
 *
 * Speichert die gewaehlte Sprache im localStorage.
 * Stellt eine t()-Funktion bereit die Uebersetzungen liefert.
 */

import * as React from 'react';

export type Locale = 'de' | 'en';

interface LanguageContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
}

const LanguageContext = React.createContext<LanguageContextType | undefined>(undefined);

// ==================== Übersetzungen ====================

const translations: Record<Locale, Record<string, string>> = {
  de: {
    // Landing Page
    'landing.welcome': 'Willkommen auf der neuen',
    'landing.platform': 'Event Experience Platform',
    'landing.subtitle': 'Die neue App für die Organisation von Deloitte Events.',
    'landing.devby': 'Entwickelt von Eike Brenneisen, Andreas Enk und Nils Felten.',
    'landing.start': 'Start',
    'landing.about': 'Die Event Experience Platform ist eine Lösung zur Verwaltung von Teilnehmern bei Deloitte-Events. Entwickelt von Eike Brenneisen, Andreas Enk und Nils Felten. Aktuell in der Pilotphase.',
    'eventlist.title': 'Deine Events',
    'eventlist.hint': 'Hier siehst du die Events, die für dich zur Registrierung verfügbar sind. Manche Events sind möglicherweise nur für bestimmte Standorte oder Unternehmensbereiche sichtbar.',
    'eventlist.onlyactive': 'Nur aktive Events',

    // Start Page
    'start.title': 'Event Experience Platform',
    'start.register': 'Registrierung',
    'start.register.desc': 'Melde dich für ein Event an',
    'start.myevents': 'Meine Events',
    'start.myevents.desc': 'Deine Anmeldungen verwalten',
    'start.admin': 'Admin',
    'start.admin.desc': 'Events verwalten',

    // Header
    'header.registration': 'Registrierung | Verfügbare Events an deinem Standort',
    'header.myevents': 'Meine Events',
    'header.createevent': 'Deloitte Event erstellen',
    'header.editevent': 'Event bearbeiten',
    'header.settings': 'Einstellungen',
    'header.profile': 'Mein Profil',
    'header.manual': 'Handbuch',
    'header.admin': 'Admin',
    'header.rolematrix': 'Rollen-Matrix',
    'header.participants': 'Teilnehmer-Übersicht',
    'header.flowcharts': 'Prozess-Übersicht',
    'header.checkin': 'Check-in',

    // Event Card
    'event.freeplaces': 'freie Plätze',
    'event.full': 'Ausgebucht',
    'event.waitlist': 'Warteliste',
    'events.until': 'bis',
    'events.regopen': 'Anmeldung bis:',
    'events.deadlinepassed': 'Frist abgelaufen',
    'events.deadlinepassed.hint': 'Bitte wende dich an den Organizer, wenn du dich noch anmelden möchtest.',

    // Registration Page
    'reg.selectedevent': 'Ausgewähltes Event',
    'reg.personalinfo': 'Persönliche Informationen',
    'reg.eventinfo': 'Event-spezifische Informationen',
    'reg.starter.title': 'B2Run Starter-Typ',
    'reg.starter.hint': 'Wähle Durchstarter (sportlich) oder Funstarter (gemütlich). Wenn ein Bereich voll ist, kannst du automatisch in den anderen wechseln.',
    'reg.starter.durch': 'Durchstarter',
    'reg.starter.durch.desc': 'Sportlich',
    'reg.starter.fun': 'Funstarter',
    'reg.starter.fun.desc': 'Gemütlich',
    'reg.starter.full': 'Voll',
    'reg.starter.free': 'frei',
    'reg.starter.required': 'Bitte wähle einen Starter-Typ (Durchstarter oder Funstarter).',
    'reg.seats.available': 'Plätze frei',
    'reg.seats.full': 'Event voll — Anmeldung geht auf die Warteliste',
    'reg.salutation': 'Anrede',
    'reg.firstname': 'Vorname',
    'reg.surname': 'Nachname',
    'reg.email': 'E-Mail',
    'reg.pleaseselect': 'Bitte wählen',
    'reg.multiselect.hint': 'Mehrere Auswahl möglich',
    'reg.userfield.notifyhint': 'Die ausgewählte Person wird per E-Mail über deine Auswahl informiert.',
    'reg.userfield.placeholder': 'Name oder E-Mail suchen…',
    'reg.thirdparty.alreadyregistered': 'Diese Person ist bereits für das Event angemeldet.',
    'reg.thirdparty.notinaudience': 'Diese Person gehört nicht zum festgelegten Verteilerkreis dieses Events.',
    'reg.required': 'Bitte ausfüllen',
    'reg.register': 'Registrieren',
    'reg.delete': 'Löschen',
    'reg.success': 'Registrierung erfolgreich!',
    'reg.error': 'Registrierung fehlgeschlagen. Möglicherweise bist du bereits angemeldet.',
    'reg.genericerror': 'Ein Fehler ist aufgetreten. Bitte versuche es erneut.',
    'reg.registerother': 'Für andere Person registrieren',
    'reg.registerself': 'Für mich selbst registrieren',
    'reg.searchemployee': 'Deloitte Mitarbeiter suchen',
    'reg.searchplaceholder': 'Name oder E-Mail eingeben...',
    'reg.requiredfield': 'Pflichtfeld',
    'reg.eventnotfound': 'Event nicht gefunden',
    'reg.backtoevents': 'Zurück zu Events',
    'reg.unlimited': 'Unbegrenzt',
    'reg.free': 'frei',
    'reg.submitting': 'Wird gesendet...',
    'reg.requiredfields': 'Bitte alle Pflichtfelder ausfüllen.',
    'reg.requiredcustom': 'Bitte ausfüllen',
    'reg.waitlisttitle': 'Auf die Warteliste gesetzt',
    'reg.waitlistmsg': 'Du wurdest auf die Warteliste für "{title}" gesetzt. Du wirst benachrichtigt, sobald ein Platz frei wird.',
    'reg.waitlistmsg.other': '{name} wurde auf die Warteliste für "{title}" gesetzt. Eine Benachrichtigung wird an {email} gesendet, sobald ein Platz frei wird.',
    'reg.successmsg': 'Du wurdest erfolgreich für "{title}" registriert. Eine Bestätigung wurde an {email} gesendet.',
    'reg.successmsg.other': '{name} wurde erfolgreich für "{title}" registriert. Eine Bestätigung wurde an {email} gesendet.',
    'reg.registeranother': 'Für ein weiteres Event registrieren',
    'reg.noadditional': 'Keine zusätzlichen Informationen erforderlich.',
    'reg.allplaces': 'Alle Plätze sind belegt. Aktuell stehen {count} Personen auf der Warteliste',
    'reg.locationnotice': 'Hinweis: Du würdest dieses Event als normaler User nicht sehen.',
    'reg.locationfilter': 'Standort-Filter',
    'reg.audience': 'Zielgruppe',
    'reg.andmode': 'UND-Verknüpfung',
    'reg.yourlocation': 'Dein Standort',
    'reg.unknown': 'unbekannt',
    'reg.until': 'bis',
    'reg.deadlinepassed.title': 'Anmeldefrist abgelaufen',
    'reg.deadlinepassed.text': 'Die Anmeldefrist für dieses Event ist leider abgelaufen. Du kannst dich nicht mehr registrieren.',
    'reg.deadlinepassed.date': 'Anmeldeschluss war',
    'reg.deadlinepassed.adminnotice': 'Hinweis: Als normaler User könntest du dich nicht mehr registrieren - die Anmeldefrist ist abgelaufen.',
    'reg.privacy': 'Im Rahmen des Events {title} werden von Deloitte Audio-, Bild- und Videoaufnahmen erstellt. Durch die eindeutige bestätigende Handlung, z.B. Posieren oder Lächeln in die Kamera, willigst du in die Erstellung von Audio-, Bild- und Videoaufnahmen ein. Die Aufnahmen können für Deloitte-interne Veröffentlichungszwecke (z.B. DeloitteNet) verwendet werden. Die Einwilligung kann jederzeit mit Wirkung für die Zukunft und ohne negative Konsequenzen per E-Mail an privacy@deloitte.de widerrufen werden.',

    // My Events
    'myevents.title': 'Meine Events',
    'myevents.loading': 'Lade deine Registrierungen...',
    'myevents.empty': 'Du bist noch für kein Event registriert.',
    'myevents.browse': 'Events durchsuchen',
    'myevents.cancel': 'Abmelden',
    'myevents.confirming': 'Wird abgemeldet...',
    'myevents.confirmcancel': 'Abmeldung bestätigen',
    'myevents.keepreg': 'Anmeldung behalten',
    'myevents.edit': 'Angaben bearbeiten',
    'myevents.save': 'Speichern',
    'myevents.saving': 'Wird gespeichert...',
    'myevents.cancelledevents': 'Abgemeldete Events',
    'myevents.cancelledon': 'Abgemeldet am',
    'myevents.location': 'Ort',
    'myevents.date': 'Datum',
    'myevents.registeredon': 'Angemeldet am',
    'myevents.agenda': 'Programm',
    'myevents.latecancel': 'Achtung: Die Abmeldefrist ist abgelaufen. Der Organizer wird über deine Abmeldung informiert.',

    // Admin Page
    'admin.title': 'Admin / Organizer',
    'admin.splist': 'SharePoint-Liste',
    'admin.newevent': 'Neues Event erstellen',
    'admin.noaccess.title': 'Noch kein Event zugeordnet',
    'admin.noaccess.msg': 'Du bist als Organizer registriert, aber bei keinem Event als Organizer oder QR-Scanner eingetragen. Erstelle dein erstes Event — oder bitte einen Admin, dich als Organizer für ein bestehendes Event einzutragen.',
    'admin.participants': 'Teilnehmer',
    'admin.processes': 'Prozesse',
    'admin.noevents': 'Keine Events vorhanden.',
    'admin.eventdetails': 'Event-Details',
    'admin.editbutton': 'Event bearbeiten',
    'admin.opensp': 'Teilnehmerliste in SharePoint öffnen',
    'admin.copyemails': 'E-Mail-Adressen kopieren',
    'admin.copied': 'Kopiert!',
    'admin.emailall': 'E-Mail an alle Teilnehmer',
    'admin.deleteevent': 'Event löschen',
    'admin.confirmdelete': 'Wirklich löschen?',
    'admin.deleting': 'Wird gelöscht...',
    'admin.checkin': 'Check-In starten',
    'admin.sendqr': 'QR-Codes versenden',
    'admin.sendingqr': 'QR-Codes werden versendet...',
    'admin.loadingregs': 'Lade Teilnehmer...',
    'admin.noregs': 'Noch keine Teilnehmer registriert.',

    // Status
    'status.registered': 'Angemeldet',
    'status.qrsent': 'QR versendet',
    'status.waitlist': 'Warteliste',
    'status.checkedin': 'Eingecheckt',
    'status.cancelled': 'Abgemeldet',

    // Event Creation
    'create.title': 'Event erstellen',
    'create.eventtitle': 'Event-Titel',
    'create.eventtype': 'Event Typ',
    'create.description': 'Beschreibung',
    'create.location': 'Ort / Venue',
    'create.organizer': 'Organizer (Name)',
    'create.organizer.placeholder': 'Name oder E-Mail eingeben und aus der Liste auswählen',
    'create.qrscanners': 'QR-Code-Scanner',
    'create.qrscanners.hint': 'Optional: Personen, die beim Event nur QR-Codes scannen und die Check-In-KPIs sehen dürfen. Sie haben KEINE weiteren Admin-Rechte (kein Edit, keine Mails, keine Teilnehmerliste), erscheinen NICHT in der Organizer-Liste auf MyEvents/Registrierungsseite und bekommen KEINE Organizer-Mails.',
    'create.qrscanners.placeholder': 'Name oder E-Mail eingeben und aus der Liste auswählen',
    'header.checkin.bubble': 'Jetzt einchecken',
    'create.startdate': 'Start (Datum & Uhrzeit)',
    'create.enddate': 'Ende (Datum & Uhrzeit)',
    'create.deadline': 'Anmelde-Deadline',
    'create.lastcancel': 'Letzte Abmeldemöglichkeit',
    'create.maxparticipants': 'Maximale Teilnehmerzahl',
    'create.maxparticipants.hint': 'Die Obergrenze, ab der die Anmeldung nicht mehr in den Status „Angemeldet" geht. Wenn keine harte Grenze nötig ist (z.B. ein Webinar ohne Platzlimit), den „Unbegrenzt"-Schalter aktivieren — dann kann jeder rein, eine Warteliste gibt es nicht.',
    'create.splitcap.label': 'Lauf-Event mit getrennten Starter-Kapazitäten',
    'create.splitcap.hint': 'Sonderfall für Läufe wie B2Run: zwei separate Töpfe (Durchstarter / Funstarter) mit jeweils eigener Kapazität und eigener Warteliste. Wenn deaktiviert, gilt eine einzige Gesamt-Teilnehmerzahl.',
    'create.waitlist': 'Warteliste',
    'create.enabled': 'Aktiviert',
    'create.disabled': 'Deaktiviert',
    'create.outlookbody': 'Outlook-Termin Text',
    'create.customfields': 'Zusätzliche Registrierungsfelder',
    'create.addfield': 'Feld hinzufügen',
    'create.fieldname': 'Feldname',
    'create.addoption': '+ Option hinzufügen',
    'create.required': 'Pflicht',
    'create.cancel': 'Abbrechen',
    'create.preview': 'Vorschau anzeigen',
    'create.registerpreview': 'Registrierungsseite vorschauen',
    'create.next': 'Weiter',
    'create.submit': 'Event erstellen',
    'create.save': 'Änderungen speichern',
    'create.step.basics': 'Grundlagen',
    'create.step.datetime': 'Zeit & Ort',
    'create.step.capacity': 'Kapazität',
    'create.step.fields': 'Felder',
    'create.step.communication': 'Kommunikation',
    'create.template': 'Vorlage',
    'create.template.hint': 'Vorlage für das Event. B2Run legt automatisch die für die Anmeldung bei b2run.com benötigten Felder an.',
    'create.template.blank': 'Leer',
    'create.template.blank.desc': 'Eigene Felder definieren',
    'create.template.b2run': 'B2Run',
    'create.template.b2run.desc': 'Alle B2Run-Pflichtfelder',
    'create.startblocks': 'Startblöcke (für B2Run)',
    'create.startblocks.hint': 'Definierte Startblöcke für dieses B2Run Event. Teilnehmer wählen einen der Blöcke bei der Anmeldung.',
    'create.startblocks.add': 'Startblock hinzufügen',
    'create.startblocks.placeholder': 'z.B. 17:00 Uhr Durchstarter (Orange)',
    'create.startblocks.remove': 'Entfernen',
    'create.b2runcap': 'B2Run Kapazitäten',
    'create.b2runcap.hint': 'Getrennte Kapazitäten für Durchstarter und Funstarter. Die Gesamtkapazität ergibt sich automatisch aus der Summe.',
    'create.b2runcap.desc': 'Teilnehmer wählen bei der Anmeldung zwischen Durchstarter und Funstarter. Wenn ein Bereich voll ist, können sie alternativ den anderen nehmen.',
    'create.b2runcap.durchstarter': 'Durchstarter',
    'create.b2runcap.funstarter': 'Funstarter',
    'create.b2runcap.total': 'Gesamt',
    'create.b2runcap.seats': 'Plätze',
    'create.b2runcap.waitlist.hint': 'Wenn aktiviert, können sich Teilnehmer auf die Warteliste setzen wenn beide Kategorien voll sind.',
    'create.eventtitle.hint': 'Name des Events, z.B. \'Office Event 2026\'. Dieser Titel wird auch für die Outlook-Termin-Einladung, die Bestätigungs-Mails und alle weiteren Kommunikationen verwendet — also sprechend wählen.',
    'create.eventtype.hint': 'Kategorie des Events – bestimmt das Design der Event-Karte',
    'create.organizer.hint': 'Name der Person, die das Event organisiert',
    'create.description.hint': 'Beschreibung des Events – wird den Teilnehmern auf der Registrierungsseite angezeigt',
    'create.eventimage': 'Event-Bild',
    'create.eventimage.hint': 'Wird als Hintergrundbild auf der Event-Karte angezeigt. Empfohlen: 800x400px, max. 5MB.',
    'create.location.hint': 'Adresse oder Name des Veranstaltungsortes',
    'create.address.hint': 'Strukturierte Adresse - wird auf der Registrierungsseite angezeigt',
    'create.startdate.hint': 'Datum und Uhrzeit werden für den Outlook-Kalendereintrag verwendet',
    'create.enddate.hint': 'Datum und Uhrzeit werden für den Outlook-Kalendereintrag verwendet',
    'create.agenda.hint': 'Programmablauf / Timeline des Events',
    'create.transfers.hint': 'Abfahrtszeiten pro Standort',
    'create.deadline.hint': 'Bis wann können sich Teilnehmer anmelden?',
    'create.lastcancel.hint': 'Bis zu diesem Stichtag können sich Teilnehmer ohne Rückfrage selbst abmelden. Danach geht eine Abmeldung zwar weiterhin durch, der oder die Organizer bekommen aber automatisch eine Late-Cancel-Mail mit Name + E-Mail des Abmeldenden — damit ihr ggf. Hotel/Catering/Bus nachjustieren könnt. Wenn du diese automatische Benachrichtigung NICHT willst, deaktiviere sie unter Schritt 5 (Kommunikation) per "Verspätete Abmeldungen an Organizer melden".',
    'create.waitlist.hint': 'Wenn aktiviert, können sich Teilnehmer auch nach Erreichen der maximalen Teilnehmerzahl anmelden (Status: Warteliste). Sobald jemand absagt, rückt automatisch der älteste Wartelisten-Eintrag nach — bekommt eine Nachrück-Mail mit Outlook-Termin und der Status wechselt auf „Angemeldet". Bei B2Run-Events mit getrennten Starter-Kapazitäten gibt es eine eigene Warteliste pro Starter-Typ; das Nachrücken erfolgt typ-bewusst (Durchstarter rücken in Durchstarter-Plätze nach, Funstarter in Funstarter-Plätze).',
    'create.error.required': 'Pflichtfeld',
    'create.error.endBeforeStart': 'Das Enddatum muss nach dem Startdatum liegen.',
    'create.error.deadlineAfterStart': 'Die Anmelde-Deadline muss vor dem Startdatum liegen.',
    'create.error.deregAfterStart': 'Die Abmeldefrist muss vor dem Startdatum liegen.',
    'create.emaillanguage': 'E-Mail Sprache',
    'create.emaillanguage.hint': 'Alle automatischen E-Mails (Anmeldung, Abmeldung, Nachrücken) werden in dieser Sprache versendet.',
    'create.fictive': 'Als Entwurf speichern',
    'create.fictive.hint': 'Standardmäßig aktiv. Solange dieses Häkchen gesetzt ist, sehen nur Admins, die eingetragenen Organizer und das im Admin-Center hinterlegte Test-Team das Event und können sich anmelden. Reguläre User sehen das Event NICHT — also kann auch niemand versehentlich registriert werden, bevor du fertig bist. Wenn du alles geprüft hast und live gehen willst, einfach das Häkchen wegnehmen und speichern.',
    'create.fictive.badge': 'ENTWURF',
    'create.eventlogo': 'Event-Logo für E-Mails und Outlook-Termin (optional)',
    'create.eventlogo.hint': 'Ersetzt das DEX-Logo in E-Mail Header und Outlook-Termin. Deloitte-Logo bleibt immer. Max. 600px breit, wird automatisch komprimiert.',
    'create.eventlogo.mail': 'Event-Logo für E-Mails (optional)',
    'create.eventlogo.mail.hint': 'Ersetzt das DEX-Logo im E-Mail-Header der automatischen Anmelde-, Warteliste- und Abmelde-Mails. Für Mails ist meist das neutrale DEX-Logo empfehlenswert. Max. 600px breit, wird automatisch komprimiert.',
    'create.outlooklogo': 'Event-Logo für Outlook-Termin (optional)',
    'create.outlooklogo.hint': 'Ersetzt das DEX-Logo im Outlook-Termin-Body. Hier kann ein event-spezifisches Bild (z.B. Veranstaltungsfoto) hochgeladen werden — das Deloitte-Logo im Header bleibt immer. Max. 600px breit.',
    'reg.audience.more': 'weitere E-Mail-Adressen',
    'create.eventlogo.select': 'Bild auswählen',
    'create.eventlogo.remove': 'Entfernen',
    'create.logoupload.warning': 'Hinweis zum Bild-Upload\n\nFür Mail- und Outlook-Logos bitte KEINE Stockfotos oder komplexen Fotos hochladen — die Mail-Layouts können solche Bilder nicht zuverlässig darstellen, das Ergebnis sieht oft pixelig oder kaputt aus.\n\nNutze stattdessen die offiziellen Deloitte Circular Motifs (einfache, runde Grafiken). Damit wirken die Mails sauber und konsistent zum Deloitte-Branding.\n\nMit "OK" trotzdem hochladen, mit "Abbrechen" das Bild ersetzen.',
    'create.outlookdesc': 'Outlook-Termin Beschreibung',
    'create.outlookdesc.edit': 'Bearbeiten & Vorschau',
    'create.outlookdesc.placeholder': 'Text für den Outlook-Kalendereintrag (optional)...',
    'create.notifications': 'Benachrichtigungen',
    'create.notifications.hint': 'Bei deaktivierten Optionen werden bei An- oder Abmeldungen keine Einträge in die DEX_Emails- bzw. DEX_Outlook-Warteschlange geschrieben.',
    'create.notifications.email': 'E-Mails versenden',
    'create.notifications.email.desc': 'Anmelde-, Abmelde-, Warteliste- und Nachrück-E-Mails',
    'create.notifications.outlook': 'Outlook-Kalendereintrag senden',
    'create.notifications.outlook.desc': 'Einladung bei Anmeldung, Ausladung bei Abmeldung',
    'create.notifications.triggerupdate': 'Outlook-Termin aktualisieren (Titel / Start / Ende / Body)',
    'create.notifications.triggerupdate.desc': 'Nur aktivieren wenn Titel, Startzeit, Endzeit oder der Termin-Body wirklich geändert wurden. Bei Aktivierung erhalten alle angemeldeten Teilnehmer automatisch eine „Updated meeting"-Benachrichtigung von Outlook. Standardmäßig ausgeschaltet, damit Tippfixes in Description/Agenda keine Update-Mails auslösen.',
    'create.templates.title': 'E-Mail Vorlagen',
    'create.templates.hint': 'Platzhalter: {{Name}} = Teilnehmername, {{EventTitle}} = Event-Titel. Änderungen gelten nur für dieses Event.',
    'create.templates.subject': 'Betreff',
    'create.templates.heading': 'Überschrift',
    'create.templates.content': 'Inhalt',
    'create.templates.edit': 'Bearbeiten',
    'create.templates.close': 'Schließen',
    'create.templates.reset': 'Zurücksetzen',
    'create.templates.modified': 'angepasst',
    'create.tpl.Anmeldung': 'Anmeldebestätigung',
    'create.tpl.Warteliste': 'Warteliste-Bestätigung',
    'create.tpl.Abmeldung': 'Abmeldebestätigung',
    'create.tpl.Nachrücken': 'Nachrücken',
    'create.tpl.Nachruecken': 'Nachrücken',
    'create.agenda': 'Agenda',
    'create.agenda.add': 'Programmpunkt hinzufügen',
    'create.agenda.icon': 'Icon',
    'create.agenda.date': 'Datum',
    'create.agenda.time': 'Uhrzeit',
    'create.agenda.endtime': 'Ende',
    'create.agenda.title': 'Titel',
    'create.agenda.desc': 'Beschreibung (optional)',
    'create.transfers': 'Transferzeiten',
    'create.transfers.add': 'Transferzeit hinzufügen',
    'create.transfers.location': 'Standort',
    'create.transfers.date': 'Datum',
    'create.transfers.departure': 'Abfahrt',
    'create.transfers.arrival': 'Ankunft',
    'create.transfers.meetingpoint': 'Treffpunkt',
    'create.transfers.address': 'Adresse',
    'create.transfers.desc': 'Zusatzinfo (optional)',
    'create.subevents': 'Sub-Events (optional)',
    'create.subevents.hint': 'Zusätzliche Sessions zum Hauptevent (z.B. Trainingssessions). Jede Session bekommt eine eigene An-/Abmelde-Mail und einen eigenen Outlook-Kalendereintrag — beides im Deloitte-Layout. Teilnehmer melden sich nach der Hauptevent-Anmeldung einzeln pro Session an.',
    'create.subevents.empty': 'Keine Sub-Events angelegt.',
    'create.subevents.add': 'Sub-Event hinzufügen',
    'create.subevents.remove': 'Entfernen',
    'create.subevents.untitled': 'Session ohne Titel',
    'create.subevents.title': 'Titel',
    'create.subevents.title.placeholder': 'z.B. Trainingssession Woche 3',
    'create.subevents.location': 'Ort',
    'create.subevents.location.placeholder': 'z.B. Deloitte Köln, Magnusstraße 13',
    'create.subevents.start': 'Start',
    'create.subevents.end': 'Ende',
    'create.subevents.deadline': 'Anmeldeschluss (optional)',
    'create.subevents.max': 'Max. Teilnehmer (0 = unbegrenzt)',
    'create.subevents.description': 'Beschreibung (optional)',
    'create.subevents.emails': 'Anmelde-/Abmelde-Mails versenden',
    'create.subevents.outlook': 'Eigenen Outlook-Kalendereintrag erzeugen',
    'reg.subevents.title': 'Zusätzliche Sessions',
    'reg.subevents.hint': 'Sessions kannst du unabhängig vom Haupt-Event an- und abmelden — du musst dich nicht zwangsläufig auch für das Haupt-Event anmelden. Pro Session bekommst du eine eigene Bestätigungs-E-Mail und einen eigenen Outlook-Kalendereintrag.',
    'reg.subevents.untitled': 'Session ohne Titel',
    'reg.subevents.register': 'Anmelden',
    'reg.subevents.cancel': 'Abmelden',
    'reg.subevents.registered': 'Angemeldet',
    'reg.subevents.start': 'Start',
    'reg.subevents.end': 'Ende',
    'reg.subevents.location': 'Ort',
    'reg.subevents.capacity': 'Plätze',
    'reg.subevents.full': 'voll',
    'reg.subevents.taken': 'vergeben',
    'reg.subevents.sessionfull': 'Diese Session ist voll.',
    'reg.subevents.deadlinepassed': 'Anmeldeschluss für diese Session ist abgelaufen.',
    'create.b2runcap.starterblock.title': 'Starter-Typ → Startblock-Zuordnung',
    'create.b2runcap.starterblock.hint': 'Wenn gesetzt: der Startblock wird bei der Registrierung automatisch anhand des gewählten Starter-Typs gesetzt — der User wählt ihn nicht extra. Freie Plätze pro Starter-Typ entsprechen den freien Plätzen im zugeordneten Block.',
    'create.b2runcap.starterblock.none': '— kein automatischer Block —',
    'create.b2runcap.proof.title': 'Leistungsnachweis für Durchstarter erforderlich',
    'create.b2runcap.proof.hint': 'Wenn aktiv, muss der User beim Wählen von Durchstarter zusätzlich bestätigen, dass ein entsprechender Leistungsnachweis vorliegt.',
    'reg.starter.proof': 'Leistungsnachweis vorhanden',
    'reg.starter.proof.hint': 'Ich bestätige, dass ein entsprechender Leistungsnachweis (z.B. Wettkampfergebnis, Trainingsnachweis) vorliegt.',
    'reg.starter.proof.required': 'Bitte Leistungsnachweis bestätigen.',
    'reg.selection.title': 'Wofür möchtest du dich anmelden?',
    'reg.selection.hint': 'Haupt-Event und Sessions können unabhängig voneinander an- oder abgewählt werden.',
    'reg.selection.mainevent': 'Haupt-Event',
    'reg.selection.sessions': 'Sessions',
    'reg.selection.alreadyregistered': 'Du bist bereits für das Haupt-Event angemeldet.',
    'reg.selection.sessionsonlyhint': 'Du meldest dich ausschließlich für Sessions an — NICHT für das Haupt-Event.',
    'reg.selection.starterinherited': 'Starter-Typ wird vom Haupt-Event übernommen ({type}).',
    'reg.selection.sessioncount.one': 'Session',
    'reg.selection.sessioncount.many': 'Sessions',
    'reg.nothing.selected': 'Bitte wähle mindestens das Haupt-Event oder eine Session aus.',
    'reg.sessions.starter.required': 'Bitte für jede ausgewählte Session den Starter-Typ (Durchstarter/Funstarter) wählen.',
    'reg.success.sessionsonly.title': 'Für Sessions angemeldet',
    'reg.success.sessionsonly.msg': 'Du hast dich ausschließlich für die ausgewählten Sessions angemeldet — NICHT für das Haupt-Event "{title}". Du bekommst pro Session eine separate Bestätigungsmail und einen eigenen Outlook-Kalendereintrag.',
    'myevents.sessionsonly.badge': 'Nur Sessions',
    'myevents.sessionsonly.hint': 'Du bist für Sessions dieses Events angemeldet, aber NICHT für das Haupt-Event selbst.',
    'create.step.documents': 'Dokumente',
    'create.documents.upload': 'Dokument hochladen',
    'create.documents.hint': 'Organisatorische Informationen, Agendas, Anfahrtsbeschreibungen etc. Teilnehmer können diese unter "Meine Events" herunterladen.',
    'myevents.transfers': 'Transferzeiten',
    'myevents.documents': 'Dokumente',
    'create.step.funzone': 'Fun-Zone',
    'create.funzone.hint': 'Erstelle ein Quiz für die Teilnehmer. Sie können es unter "Meine Events" spielen.',
    'create.funzone.question': 'Frage',
    'create.funzone.questionplaceholder': 'Deine Frage eingeben...',
    'create.funzone.options': 'Antwortmöglichkeiten (richtige Antwort markieren)',
    'create.funzone.option': 'Option',
    'create.funzone.correct': 'Richtige Antwort',
    'create.funzone.correcthint': 'Markiere die richtigen Antworten mit den Checkboxen links. Mehrfachauswahl möglich.',
    'create.funzone.addoption': 'Option hinzufügen',
    'create.funzone.addquestion': 'Frage hinzufügen',

    // Check-in
    'checkin.title': 'Check-in',
    'checkin.scan': 'QR-Code scannen',
    'checkin.manual': 'Oder Code manuell eingeben:',
    'checkin.check': 'Prüfen',
    'checkin.scanning': 'Scanne QR-Code...',
    'checkin.cancelscanning': 'Abbrechen',
    'checkin.invalidqr': 'Ungültiger QR-Code.',
    'checkin.notfound': 'nicht gefunden.',
    'checkin.notregistered': 'ist nicht für dieses Event registriert.',
    'checkin.checkinbtn': 'Einchecken',
    'checkin.checkingIn': 'Wird eingecheckt...',
    'checkin.success': 'Erfolgreich eingecheckt!',
    'checkin.alreadycheckedin': 'Bereits eingecheckt',
    'checkin.cancelled': 'Teilnehmer ist abgemeldet — Check-in nicht möglich',
    'checkin.next': 'Nächsten Teilnehmer scannen',
    'checkin.sessioncount': 'eingecheckt in dieser Session',

    // Profile
    'profile.details': 'Profil Details',
    'profile.firstname': 'Vorname',
    'profile.lastname': 'Nachname',
    'profile.jobtitle': 'Titel / Position',
    'profile.department': 'Abteilung',
    'profile.office': 'Standort',
    'profile.email': 'E-Mail',
    'profile.phone': 'Telefon',
    'profile.mobile': 'Mobiltelefon',
    'profile.manager': 'Manager',
    'profile.note': 'Diese Daten werden aus deinem SharePoint-Profil gelesen. Um sie zu aktualisieren, wende dich an deine IT oder aktualisiere dein Profil in Microsoft 365.',
    'profile.viewfull': 'Profil anzeigen',

    // Settings
    'settings.title': 'Einstellungen',
    'settings.rolemanagement': 'Rollenverwaltung',

    // Participants
    'participants.title': 'Teilnehmer-Übersicht',
    'participants.opensp': 'In SharePoint öffnen',
    'participants.search': 'Teilnehmer suchen (Name oder E-Mail)...',
    'participants.loading': 'Lade Teilnehmer...',
    'participants.empty': 'Noch keine Teilnehmer registriert.',
    'participants.noresults': 'Keine Teilnehmer gefunden.',
    'participants.registered': 'Registriert',
    'participants.waitlist': 'Warteliste',

    // General
    'general.event': 'Event',
    'general.back': 'Zurück',
    'general.cancel': 'Abbrechen',
    'general.save': 'Speichern',
    'general.delete': 'Löschen',
    'general.close': 'Schließen',
    'general.yes': 'Ja',
    'general.no': 'Nein',
    'general.of': 'von',
    'general.filtered': 'gefiltert',
  },

  en: {
    // Landing Page
    'landing.welcome': 'Welcome to the new',
    'landing.platform': 'Event Experience Platform',
    'landing.subtitle': 'The new app for organising Deloitte events.',
    'landing.devby': 'Built by Eike Brenneisen, Andreas Enk and Nils Felten.',
    'landing.start': 'Start',
    'landing.about': 'The Event Experience Platform is a solution for managing participants at Deloitte events. Developed by Eike Brenneisen, Andreas Enk and Nils Felten. Currently in pilot phase.',
    'eventlist.title': 'Your events',
    'eventlist.hint': 'Here are the events available for your registration. Some events might only be visible for certain locations or business areas.',
    'eventlist.onlyactive': 'Only active events',

    // Start Page
    'start.title': 'Event Experience Platform',
    'start.register': 'Registration',
    'start.register.desc': 'Register for an event',
    'start.myevents': 'My Events',
    'start.myevents.desc': 'Manage your registrations',
    'start.admin': 'Admin',
    'start.admin.desc': 'Manage events',

    // Header
    'header.registration': 'Registration | Available events at your location',
    'header.myevents': 'My Events',
    'header.createevent': 'Deloitte Event Creation',
    'header.editevent': 'Edit Event',
    'header.settings': 'Settings',
    'header.profile': 'My Profile',
    'header.manual': 'Handbook',
    'header.admin': 'Admin',
    'header.rolematrix': 'Role Matrix',
    'header.participants': 'Participants Overview',
    'header.flowcharts': 'Process Overview',
    'header.checkin': 'Check-in',

    // Event Card
    'event.freeplaces': 'free places',
    'event.full': 'Fully booked',
    'event.waitlist': 'Waitlist',
    'events.until': 'until',
    'events.regopen': 'Registration open until:',
    'events.deadlinepassed': 'Registration closed',
    'events.deadlinepassed.hint': 'Please contact the organizer if you still want to register.',

    // Registration Page
    'reg.selectedevent': 'Selected Event',
    'reg.personalinfo': 'Personal Information',
    'reg.eventinfo': 'Event specific Information',
    'reg.starter.title': 'B2Run Starter type',
    'reg.starter.hint': 'Choose Sprinter (sporty) or Funstarter (relaxed). If one category is full, you can automatically switch to the other.',
    'reg.starter.durch': 'Sprinter',
    'reg.starter.durch.desc': 'Sporty',
    'reg.starter.fun': 'Funstarter',
    'reg.starter.fun.desc': 'Relaxed',
    'reg.starter.full': 'Full',
    'reg.starter.free': 'free',
    'reg.starter.required': 'Please choose a starter type (Sprinter or Funstarter).',
    'reg.seats.available': 'seats available',
    'reg.seats.full': 'Event full — you will be placed on the waitlist',
    'reg.salutation': 'Salutation',
    'reg.firstname': 'First Name',
    'reg.surname': 'Surname',
    'reg.email': 'E-Mail',
    'reg.pleaseselect': 'Please select',
    'reg.multiselect.hint': 'Multiple selections allowed',
    'reg.userfield.notifyhint': 'The selected person will be notified about your choice via email.',
    'reg.userfield.placeholder': 'Search by name or email…',
    'reg.thirdparty.alreadyregistered': 'This person is already registered for this event.',
    'reg.thirdparty.notinaudience': 'This person is not part of the defined audience for this event.',
    'reg.required': 'Please fill in',
    'reg.register': 'Register',
    'reg.delete': 'Delete',
    'reg.success': 'Registration successful!',
    'reg.error': 'Registration failed. You may already be registered.',
    'reg.genericerror': 'An error occurred. Please try again.',
    'reg.registerother': 'Register for another person',
    'reg.registerself': 'Register for myself',
    'reg.searchemployee': 'Search Deloitte employee',
    'reg.searchplaceholder': 'Enter name or email...',
    'reg.requiredfield': 'Required field',
    'reg.eventnotfound': 'Event not found',
    'reg.backtoevents': 'Back to Events',
    'reg.unlimited': 'Unlimited',
    'reg.free': 'free',
    'reg.submitting': 'Submitting...',
    'reg.requiredfields': 'Please fill in all required fields.',
    'reg.requiredcustom': 'Please fill in',
    'reg.waitlisttitle': 'Added to waitlist',
    'reg.waitlistmsg': 'You have been added to the waitlist for "{title}". You will be notified when a spot becomes available.',
    'reg.waitlistmsg.other': '{name} has been added to the waitlist for "{title}". A notification will be sent to {email} when a spot becomes available.',
    'reg.successmsg': 'You have been successfully registered for "{title}". A confirmation has been sent to {email}.',
    'reg.successmsg.other': '{name} has been successfully registered for "{title}". A confirmation has been sent to {email}.',
    'reg.registeranother': 'Register for another event',
    'reg.noadditional': 'No additional information required.',
    'reg.allplaces': 'All places are taken. There are currently {count} people on the waiting list',
    'reg.locationnotice': 'Note: You would not see this event as a regular user.',
    'reg.locationfilter': 'Location filter',
    'reg.audience': 'Audience',
    'reg.andmode': 'AND combination',
    'reg.yourlocation': 'Your location',
    'reg.unknown': 'unknown',
    'reg.until': 'until',
    'reg.deadlinepassed.title': 'Registration closed',
    'reg.deadlinepassed.text': 'The registration period for this event has ended. You can no longer register.',
    'reg.deadlinepassed.date': 'Registration deadline was',
    'reg.deadlinepassed.adminnotice': 'Note: As a regular user you would no longer be able to register - the registration deadline has passed.',
    'reg.privacy': 'As part of the event {title}, audio, image, and video recordings will be made for Deloitte. By the clear confirming action, e.g., posing or smiling at the camera, you consent to the creation of audio, image, and video recordings. The recordings may be used for Deloitte internal publication purposes (e.g., DeloitteNet). The consent can be revoked at any time with future effect and without any negative consequences by sending an email to privacy@deloitte.de.',

    // My Events
    'myevents.title': 'My Events',
    'myevents.loading': 'Loading your registrations...',
    'myevents.empty': 'You are not registered for any event yet.',
    'myevents.browse': 'Browse events',
    'myevents.cancel': 'Cancel registration',
    'myevents.confirming': 'Cancelling...',
    'myevents.confirmcancel': 'Confirm cancellation',
    'myevents.keepreg': 'Keep registration',
    'myevents.edit': 'Edit details',
    'myevents.save': 'Save',
    'myevents.saving': 'Saving...',
    'myevents.cancelledevents': 'Cancelled Events',
    'myevents.cancelledon': 'Cancelled on',
    'myevents.location': 'Location',
    'myevents.date': 'Date',
    'myevents.registeredon': 'Registered on',
    'myevents.agenda': 'Schedule',
    'myevents.latecancel': 'Warning: The cancellation deadline has passed. The organizer will be notified of your cancellation.',

    // Admin Page
    'admin.title': 'Admin / Organizer',
    'admin.splist': 'SharePoint List',
    'admin.newevent': 'Create new event',
    'admin.noaccess.title': 'No event assigned yet',
    'admin.noaccess.msg': 'You have the Organizer role, but you\'re not registered as organizer or QR scanner on any event. Create your first event — or ask an admin to add you as organizer to an existing event.',
    'admin.participants': 'Participants',
    'admin.processes': 'Processes',
    'admin.noevents': 'No events found.',
    'admin.eventdetails': 'Event Details',
    'admin.editbutton': 'Edit event',
    'admin.opensp': 'Open participant list in SharePoint',
    'admin.copyemails': 'Copy email addresses',
    'admin.copied': 'Copied!',
    'admin.emailall': 'Email all participants',
    'admin.deleteevent': 'Delete event',
    'admin.confirmdelete': 'Are you sure?',
    'admin.deleting': 'Deleting...',
    'admin.checkin': 'Start check-in',
    'admin.sendqr': 'Send QR codes',
    'admin.sendingqr': 'Sending QR codes...',
    'admin.loadingregs': 'Loading participants...',
    'admin.noregs': 'No participants registered yet.',

    // Status
    'status.registered': 'Registered',
    'status.qrsent': 'QR sent',
    'status.waitlist': 'Waitlist',
    'status.checkedin': 'Checked in',
    'status.cancelled': 'Cancelled',

    // Event Creation
    'create.title': 'Create Event',
    'create.eventtitle': 'Event Title',
    'create.eventtype': 'Event Type',
    'create.description': 'Description',
    'create.location': 'Location / Venue',
    'create.organizer': 'Organizer (Name)',
    'create.organizer.placeholder': 'Type name or email and pick from the list',
    'create.qrscanners': 'QR-code scanners',
    'create.qrscanners.hint': 'Optional: users who may only scan QR codes and see check-in KPIs for this event. They have NO further admin rights (no edit, no emails, no participant list), do NOT appear in the organizer list on MyEvents/registration page, and do NOT receive organizer emails.',
    'create.qrscanners.placeholder': 'Type name or email and pick from the list',
    'header.checkin.bubble': 'Check in now',
    'create.startdate': 'Start (Date & Time)',
    'create.enddate': 'End (Date & Time)',
    'create.deadline': 'Registration Deadline',
    'create.lastcancel': 'Last Cancellation Date',
    'create.maxparticipants': 'Maximum participants',
    'create.maxparticipants.hint': 'The upper limit beyond which registrations no longer go to status „Registered". If you don\'t need a hard cap (e.g. a webinar with no seat limit), turn on the „Unlimited" switch — then anyone can register and there is no waitlist.',
    'create.splitcap.label': 'Run event with separate starter capacities',
    'create.splitcap.hint': 'Special case for runs like B2Run: two separate buckets (Durchstarter / Funstarter), each with its own capacity and its own waitlist. If disabled, a single overall participant limit applies.',
    'create.waitlist': 'Waitlist',
    'create.enabled': 'Enabled',
    'create.disabled': 'Disabled',
    'create.outlookbody': 'Outlook Calendar Text',
    'create.customfields': 'Additional Registration Fields',
    'create.addfield': 'Add field',
    'create.fieldname': 'Field name',
    'create.addoption': '+ Add option',
    'create.required': 'Required',
    'create.cancel': 'Cancel',
    'create.preview': 'Show preview',
    'create.registerpreview': 'Preview registration page',
    'create.next': 'Next',
    'create.submit': 'Create event',
    'create.save': 'Save changes',
    'create.step.basics': 'Basics',
    'create.step.datetime': 'Date & Location',
    'create.step.capacity': 'Capacity',
    'create.step.fields': 'Fields',
    'create.step.communication': 'Communication',
    'create.template': 'Template',
    'create.template.hint': 'Template for the event. B2Run automatically adds all required fields for the b2run.com registration.',
    'create.template.blank': 'Blank',
    'create.template.blank.desc': 'Define your own fields',
    'create.template.b2run': 'B2Run',
    'create.template.b2run.desc': 'All B2Run required fields',
    'create.startblocks': 'Starting blocks (for B2Run)',
    'create.startblocks.hint': 'Defined starting blocks for this B2Run event. Participants choose one of the blocks during registration.',
    'create.startblocks.add': 'Add starting block',
    'create.startblocks.placeholder': 'e.g. 17:00 Sprinters (Orange)',
    'create.startblocks.remove': 'Remove',
    'create.b2runcap': 'B2Run capacities',
    'create.b2runcap.hint': 'Separate capacities for Sprinters and Funstarters. The total capacity is the sum of both.',
    'create.b2runcap.desc': 'Participants choose between Sprinters and Funstarters at registration. If one category is full, they can switch to the other.',
    'create.b2runcap.durchstarter': 'Sprinters',
    'create.b2runcap.funstarter': 'Funstarters',
    'create.b2runcap.total': 'Total',
    'create.b2runcap.seats': 'seats',
    'create.b2runcap.waitlist.hint': 'If enabled, participants can join the waiting list when both categories are full.',
    'create.eventtitle.hint': 'Name of the event, e.g. \'Office Event 2026\'. This title is also used for the Outlook calendar invite, confirmation emails and all other communications — pick something descriptive.',
    'create.eventtype.hint': 'Category of the event – determines the design of the event card',
    'create.organizer.hint': 'Name of the person organizing the event',
    'create.description.hint': 'Description of the event – shown to participants on the registration page',
    'create.eventimage': 'Event image',
    'create.eventimage.hint': 'Displayed as the background image on the event card. Recommended: 800x400px, max. 5MB.',
    'create.location.hint': 'Address or name of the venue',
    'create.address.hint': 'Structured address - shown on the registration page',
    'create.startdate.hint': 'Date and time are used for the Outlook calendar entry',
    'create.enddate.hint': 'Date and time are used for the Outlook calendar entry',
    'create.agenda.hint': 'Program / timeline of the event',
    'create.transfers.hint': 'Departure times per location',
    'create.deadline.hint': 'Until when can participants register?',
    'create.lastcancel.hint': 'Up to this cutoff, participants can cancel themselves without consequence. After that date cancellations still go through, but the organizer(s) automatically receive a late-cancel notification with the name + email of the person — so you can adjust hotel/catering/buses if needed. If you do NOT want that automatic notification, turn it off in Step 5 (Communication) via "Notify organizer about late cancellations".',
    'create.waitlist.hint': 'If enabled, participants can still register after the maximum participant limit is reached (status: Waitlist). As soon as someone cancels, the oldest waitlist entry is automatically promoted — receives a promotion email with an Outlook invite, and the status switches to „Registered". For B2Run events with split starter capacities, each starter type has its own waitlist; promotion is type-aware (Durchstarter promote into Durchstarter slots, Funstarter into Funstarter slots).',
    'create.error.required': 'Required',
    'create.error.endBeforeStart': 'End date must be after start date.',
    'create.error.deadlineAfterStart': 'Registration deadline must be before start date.',
    'create.error.deregAfterStart': 'Cancellation deadline must be before start date.',
    'create.emaillanguage': 'E-Mail Language',
    'create.emaillanguage.hint': 'All automated emails (registration, cancellation, waitlist promotion) will be sent in this language.',
    'create.fictive': 'Save as draft',
    'create.fictive.hint': 'On by default. While this checkbox is set, only admins, the listed organizers, and the Test Team configured in the admin center see and can register for this event. Regular users won\'t see it — so nobody can accidentally sign up before you\'re ready. Once everything is verified, uncheck and save to go live.',
    'create.fictive.badge': 'DRAFT',
    'create.eventlogo': 'Event Logo for E-Mails and Outlook invite (optional)',
    'create.eventlogo.hint': 'Replaces the DEX logo in email header and Outlook calendar entry. Deloitte logo always stays. Max. 600px wide, auto-compressed.',
    'create.eventlogo.mail': 'Event Logo for E-Mails (optional)',
    'create.eventlogo.mail.hint': 'Replaces the DEX logo in the email header of automated registration, waitlist and cancellation emails. For emails, the neutral DEX logo is usually recommended. Max. 600px wide, auto-compressed.',
    'create.outlooklogo': 'Event Logo for Outlook invite (optional)',
    'create.outlooklogo.hint': 'Replaces the DEX logo in the Outlook calendar body. Upload an event-specific image (e.g. venue photo) — the Deloitte header logo always stays. Max. 600px wide.',
    'reg.audience.more': 'more email addresses',
    'create.eventlogo.select': 'Select image',
    'create.eventlogo.remove': 'Remove',
    'create.logoupload.warning': 'Image upload note\n\nFor email and Outlook logos, please do NOT upload stock photos or complex photographs — the email layouts cannot render those reliably, the result usually looks pixelated or broken.\n\nUse the official Deloitte circular motifs instead (simple, round graphics). That keeps the mails clean and on-brand.\n\nClick OK to upload anyway, Cancel to pick a different image.',
    'create.outlookdesc': 'Outlook Calendar Description',
    'create.outlookdesc.edit': 'Edit & Preview',
    'create.outlookdesc.placeholder': 'Text for the Outlook calendar entry (optional)...',
    'create.notifications': 'Notifications',
    'create.notifications.hint': 'When disabled, sign-ups and cancellations will not write entries to the DEX_Emails / DEX_Outlook queues.',
    'create.notifications.email': 'Send emails',
    'create.notifications.email.desc': 'Registration, cancellation, waitlist and promotion emails',
    'create.notifications.outlook': 'Send Outlook calendar invite',
    'create.notifications.outlook.desc': 'Invitation on sign-up, removal on cancellation',
    'create.notifications.triggerupdate': 'Update Outlook event (title / start / end / body)',
    'create.notifications.triggerupdate.desc': 'Only enable when title, start, end or body have actually changed. When enabled, all registered attendees automatically receive an "Updated meeting" notification from Outlook. Off by default so that small tweaks in description/agenda don\'t trigger update mails.',
    'create.templates.title': 'E-Mail Templates',
    'create.templates.hint': 'Placeholders: {{Name}} = participant name, {{EventTitle}} = event title. Changes apply to this event only.',
    'create.templates.subject': 'Subject',
    'create.templates.heading': 'Heading',
    'create.templates.content': 'Content',
    'create.templates.edit': 'Edit',
    'create.templates.close': 'Close',
    'create.templates.reset': 'Reset',
    'create.templates.modified': 'modified',
    'create.tpl.Anmeldung': 'Registration Confirmation',
    'create.tpl.Warteliste': 'Waitlist Confirmation',
    'create.tpl.Abmeldung': 'Cancellation Confirmation',
    'create.tpl.Nachrücken': 'Waitlist Promotion',
    'create.tpl.Nachruecken': 'Waitlist Promotion',
    'create.agenda': 'Agenda',
    'create.agenda.add': 'Add agenda item',
    'create.agenda.icon': 'Icon',
    'create.agenda.date': 'Date',
    'create.agenda.time': 'Time',
    'create.agenda.endtime': 'End',
    'create.agenda.title': 'Title',
    'create.agenda.desc': 'Description (optional)',
    'create.transfers': 'Transfer Times',
    'create.transfers.add': 'Add transfer time',
    'create.transfers.location': 'Location',
    'create.transfers.date': 'Date',
    'create.transfers.departure': 'Departure',
    'create.transfers.arrival': 'Arrival',
    'create.transfers.meetingpoint': 'Meeting Point',
    'create.transfers.address': 'Address',
    'create.transfers.desc': 'Additional info (optional)',
    'create.subevents': 'Sub-events (optional)',
    'create.subevents.hint': 'Additional sessions inside the main event (e.g. training sessions). Each session has its own registration/cancellation email and its own Outlook calendar entry — both in Deloitte layout. Attendees opt in to sessions individually after registering for the main event.',
    'create.subevents.empty': 'No sub-events added yet.',
    'create.subevents.add': 'Add sub-event',
    'create.subevents.remove': 'Remove',
    'create.subevents.untitled': 'Untitled session',
    'create.subevents.title': 'Title',
    'create.subevents.title.placeholder': 'e.g. Training session week 3',
    'create.subevents.location': 'Location',
    'create.subevents.location.placeholder': 'e.g. Deloitte Cologne, Magnusstrasse 13',
    'create.subevents.start': 'Start',
    'create.subevents.end': 'End',
    'create.subevents.deadline': 'Registration deadline (optional)',
    'create.subevents.max': 'Max. attendees (0 = unlimited)',
    'create.subevents.description': 'Description (optional)',
    'create.subevents.emails': 'Send registration/cancellation emails',
    'create.subevents.outlook': 'Create dedicated Outlook calendar entry',
    'reg.subevents.title': 'Additional sessions',
    'reg.subevents.hint': 'You can register for and cancel sessions independently of the main event — you do not have to be registered for the main event. You will receive a separate confirmation email and calendar invite per session.',
    'reg.subevents.untitled': 'Untitled session',
    'reg.subevents.register': 'Register',
    'reg.subevents.cancel': 'Cancel',
    'reg.subevents.registered': 'Registered',
    'reg.subevents.start': 'Start',
    'reg.subevents.end': 'End',
    'reg.subevents.location': 'Location',
    'reg.subevents.capacity': 'Capacity',
    'reg.subevents.full': 'full',
    'reg.subevents.taken': 'taken',
    'reg.subevents.sessionfull': 'This session is full.',
    'reg.subevents.deadlinepassed': 'Registration deadline for this session has passed.',
    'create.b2runcap.starterblock.title': 'Starter type → start block mapping',
    'create.b2runcap.starterblock.hint': 'If set: the start block is auto-assigned at registration based on the chosen starter type — the user does not pick it separately. Free seats per starter type correspond to free seats in the mapped block.',
    'create.b2runcap.starterblock.none': '— no automatic block —',
    'create.b2runcap.proof.title': 'Proof of performance required for Durchstarter',
    'create.b2runcap.proof.hint': 'When enabled, the user must confirm having a valid proof of performance when picking Durchstarter.',
    'reg.starter.proof': 'Proof of performance available',
    'reg.starter.proof.hint': 'I confirm that a valid proof of performance (e.g. race result, training record) exists.',
    'reg.starter.proof.required': 'Please confirm the proof of performance.',
    'reg.selection.title': 'What would you like to register for?',
    'reg.selection.hint': 'The main event and sessions can be selected or deselected independently.',
    'reg.selection.mainevent': 'Main event',
    'reg.selection.sessions': 'Sessions',
    'reg.selection.alreadyregistered': 'You are already registered for the main event.',
    'reg.selection.sessionsonlyhint': 'You will register for sessions only — NOT for the main event.',
    'reg.selection.starterinherited': 'Starter type inherited from main event ({type}).',
    'reg.selection.sessioncount.one': 'session',
    'reg.selection.sessioncount.many': 'sessions',
    'reg.nothing.selected': 'Please select at least the main event or one session.',
    'reg.sessions.starter.required': 'Please pick the starter type (Durchstarter/Funstarter) for each selected session.',
    'reg.success.sessionsonly.title': 'Registered for sessions',
    'reg.success.sessionsonly.msg': 'You have registered for the selected sessions only — NOT for the main event "{title}". You will receive a separate confirmation email and calendar entry for each session.',
    'myevents.sessionsonly.badge': 'Sessions only',
    'myevents.sessionsonly.hint': 'You are registered for sessions of this event but NOT for the main event itself.',
    'create.step.documents': 'Documents',
    'create.documents.upload': 'Upload document',
    'create.documents.hint': 'Organizational information, agendas, travel directions etc. Participants can download these from "My Events".',
    'myevents.transfers': 'Transfer Times',
    'myevents.documents': 'Documents',
    'create.step.funzone': 'Fun-Zone',
    'create.funzone.hint': 'Create a quiz for participants. They can play it under "My Events".',
    'create.funzone.question': 'Question',
    'create.funzone.questionplaceholder': 'Enter your question...',
    'create.funzone.options': 'Answer options (mark the correct answer)',
    'create.funzone.option': 'Option',
    'create.funzone.correct': 'Correct answer',
    'create.funzone.correcthint': 'Mark the correct answers with the checkboxes on the left. Multiple selections possible.',
    'create.funzone.addoption': 'Add option',
    'create.funzone.addquestion': 'Add question',

    // Check-in
    'checkin.title': 'Check-in',
    'checkin.scan': 'Scan QR code',
    'checkin.manual': 'Or enter code manually:',
    'checkin.check': 'Check',
    'checkin.scanning': 'Scanning QR code...',
    'checkin.cancelscanning': 'Cancel',
    'checkin.invalidqr': 'Invalid QR code.',
    'checkin.notfound': 'not found.',
    'checkin.notregistered': 'is not registered for this event.',
    'checkin.checkinbtn': 'Check in',
    'checkin.checkingIn': 'Checking in...',
    'checkin.success': 'Successfully checked in!',
    'checkin.alreadycheckedin': 'Already checked in',
    'checkin.cancelled': 'Participant is cancelled — check-in not possible',
    'checkin.next': 'Scan next participant',
    'checkin.sessioncount': 'checked in this session',

    // Profile
    'profile.details': 'Profile Details',
    'profile.firstname': 'First Name',
    'profile.lastname': 'Last Name',
    'profile.jobtitle': 'Job Title',
    'profile.department': 'Department',
    'profile.office': 'Office',
    'profile.email': 'E-Mail',
    'profile.phone': 'Phone',
    'profile.mobile': 'Mobile',
    'profile.manager': 'Manager',
    'profile.note': 'This data is read from your SharePoint profile. To update it, contact your IT or update your profile in Microsoft 365.',
    'profile.viewfull': 'View profile',

    // Settings
    'settings.title': 'Settings',
    'settings.rolemanagement': 'Role Management',

    // Participants
    'participants.title': 'Participants Overview',
    'participants.opensp': 'Open in SharePoint',
    'participants.search': 'Search participants (name or email)...',
    'participants.loading': 'Loading participants...',
    'participants.empty': 'No participants registered yet.',
    'participants.noresults': 'No participants found.',
    'participants.registered': 'Registered',
    'participants.waitlist': 'Waitlist',

    // General
    'general.event': 'Event',
    'general.back': 'Back',
    'general.cancel': 'Cancel',
    'general.save': 'Save',
    'general.delete': 'Delete',
    'general.close': 'Close',
    'general.yes': 'Yes',
    'general.no': 'No',
    'general.of': 'of',
    'general.filtered': 'filtered',
  },
};

// ==================== Provider ====================

const STORAGE_KEY = 'dex-locale';

export function LanguageProvider(props: { children: React.ReactNode }): React.ReactElement {
  const [locale, setLocaleState] = React.useState<Locale>(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      if (stored === 'de' || stored === 'en') return stored;
    } catch { /* */ }
    return 'en'; // Default: Englisch
  });

  const setLocale = (newLocale: Locale): void => {
    setLocaleState(newLocale);
    try {
      localStorage.setItem(STORAGE_KEY, newLocale);
    } catch { /* */ }
  };

  const t = (key: string): string => {
    return translations[locale][key] || translations['en'][key] || key;
  };

  return React.createElement(
    LanguageContext.Provider,
    { value: { locale, setLocale, t } },
    props.children
  );
}

export function useLanguage(): LanguageContextType {
  const ctx = React.useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
